### ISSUE TITLE
PWM deinit not working

### ISSUE THREAD

**Issue by Tasm-Devil** [adafruit/Adafruit_CircuitPython_RTTTL#13]
Hi,

I try using this helper on a nrf52840 and it works like a charm. But only the first time after softboot. The second time, CircuitPython throws a ValueError telling my, that my Pin is already in use.

It looks to me like, the last line, where the deinit() is executed, isn't doing anything.
```python
import board
import adafruit_rtttl

adafruit_rtttl.play(board.A3, "korobyeyniki:d=4,o=5,b=160:e6,8b,8c6,8d6,16e6,16d6,8c6,8b,a,8a,8c6,e6,8d6,8c6,b,8b,8c6,d6,e6,c6,a,2a,8p,d6,8f6,a6,8g6,8f6,e6,8e6,8c6,e6,8d6,8c6,b,8b,8c6,d6,e6,c6,a,a")
```

Maybe Related: [https://github.com/adafruit/Adafruit_CircuitPython_RTTTL/issues/6](https://github.com/adafruit/Adafruit_CircuitPython_RTTTL/issues/6)

**Comment by tannewt** [comment]
Would you mind trying to reproduce this without the library? Feels like a CircuitPython core bug to me.

**Comment by kattni** [comment]
@Tasm-Devil Are you still experiencing this issue?
